import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/Components/Navbar';
import checkIcon from '../Images/checkIcon.svg';
import Footer from '@/Components/Footer';
import Accordion from '@/Components/Accordion';
import { price_plans } from '../Utils/Constant';
export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing | StartX Finance</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />

      {/* hero-section */}

      <section className='hero_container'>
        <div className='main-container'>
          <div className='text_white padding_top'>
            <h3 className='heading_3 text_center'>
              Simple plans, low monthly prices
            </h3>
            <p className='text_center'>
              Enjoy 1 month free trial. Change or cancel your plan at any time.
            </p>
            <div className='cards_container  text_black'>
              {price_plans?.map((item, i) => (
                <div key={i} className='pricing_card'>
                  <h3 className='heading_4 text_center'>{item.title}</h3>
                  <p
                    className='paragraph_1 text_center'
                    style={{ height: '20px' }}
                  >
                    {item.tagline}
                  </p>
                  <div className='card_text_container text_center'>
                    <h5 className='heading_5'>{item.price}</h5>
                    <button
                      className={`${
                        item.price === 'Free forever'
                          ? 'secondary_outline'
                          : 'primary-button width-full'
                      } btn_margin cursor_pointer`}
                    >
                      {item.cta.title}
                    </button>
                  </div>
                  {item.benefits.map((benefit, i) => (
                    <div className='points_container'>
                      <img src={checkIcon.src} alt='checkIcon' />
                      <p className='paragraph_1'>{benefit}</p>
                    </div>
                  ))}
                </div>
              ))}
            </div>

            <div className='connect_section'>
              <p style={{ fontSize: '36px', fontWeight: 500, margin: 0 }}>
                Connect
              </p>
              <p
                style={{
                  textAlign: 'center',
                  fontSize: '18px',
                  fontWeight: 500,
                  margin: 0,
                }}
              >
                Send Shelf and Xplore orders
                <br />
                straight to your broker
              </p>
              <p style={{ fontSize: '30px', fontWeight: 300, margin: 0 }}>
                +$10/month
              </p>
            </div>
          </div>
        </div>
        <div className='hero_background'></div>
      </section>
      <div className='investBackground'>
        <Accordion />

        {/* Get essential investing tips */}
        <div
          className=''
          style={{
            width: '100%',
            textAlign: 'center',
            // alignItems: "center",
            // justifyContent: "center",
            margin: '20px 0',
            // gap: "10px",
            color: 'white',
          }}
        >
          <div>
            <p style={{ fontWeight: 600, fontSize: '50px', margin: 0 }}>
              GET ESSENTIAL <br /> INVESTING TIPS
            </p>
            <p style={{ fontWeight: 400, fontSize: '14px', margin: 0 }}>
              SUBSCRIBE TO OUR NEWSLETTER FOR FREE TODAY
            </p>
          </div>
          <div
            className=''
            // style={{
            //   // display: 'flex',
            //   gap: "10px",
            //   backgroundImage: `url(${curveBlackImage.src})`,
            //   backgroundRepeat: "no-repeat",
            //   backgroundSize: "cover",
            //   width: "100%",
            //   height: "100vh",
            // }}
          >
            <input
              type='email'
              placeholder='Enter your e-mail address'
              style={{ height: '30px' }}
            />
            <button className='primary-button'>SIGN UP</button>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
