import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='main-container connect_section'>
        <p style={{ fontSize: '36px', fontWeight: 500, margin: 0 }}>Connect</p>
        <p
          style={{
            textAlign: 'center',
            fontSize: '18px',
            fontWeight: 500,
            margin: 0,
          }}
        >
          Send Shelf and Xplore orders
          <br />
          straight to your broker
        </p>
        <p style={{ fontSize: '30px', fontWeight: 300, margin: 0 }}>
          +$10/month
        </p>
      </div>
      <Footer />
    </>
  );
}
